<a href="https://colab.research.google.com/github/wp-jackliu/Pytorch-Tutorial-Demo/blob/main/pytorch01_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

## 这是学习 pytorch 的开始

哈哈, 这个入门即可,不要被数学公式迷惑,因为我们目前的第一个目标是入门,入门,入门.而不是学者.

In [ ]:
import torch
import numpy as np

In [ ]:
!pip list

List


In [ ]:
my_list=[[1,2,3,4,5,6],[7,8,9,10,11]]
my_list

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11]]

Array


In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.97203911, 0.49033025, 0.16745559, 0.42906647],
       [0.89539819, 0.13860762, 0.98877229, 0.62733521],
       [0.79778314, 0.43394631, 0.04832866, 0.52171209]])

np1.dtype

In [ ]:
np1.dtype

dtype('float64')

#Tensors


In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.0068,  0.8001,  0.9662, -0.4854],
        [ 0.8196,  0.2378,  1.1060, -0.9193],
        [ 0.0423,  0.2142,  0.8192, -0.8752]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## Create tensor  out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9720, 0.4903, 0.1675, 0.4291],
        [0.8954, 0.1386, 0.9888, 0.6273],
        [0.7978, 0.4339, 0.0483, 0.5217]], dtype=torch.float64)

In [ ]:
my_torch1= torch.arange(10)
my_torch1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch1 = my_torch1.reshape(2,5)
my_torch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch1 = my_torch1.reshape(2,-1)
my_torch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])