<a href="https://colab.research.google.com/github/wp-jackliu/Pytorch-Tutorial-Demo/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensor 数学计算


In [19]:
import torch
import numpy as np

In [20]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [21]:
# 加法
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
# add Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
# Subtraction
tensor_b - tensor_a


tensor([4, 4, 4, 4])

In [27]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [28]:
# Reminder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [29]:
# Exponents / power 指数   like 2^3
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [30]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [31]:
tensor_a

tensor([1, 2, 3, 4])

In [32]:
# import _
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [33]:
tensor_a
#使用上述方式后,变化了.

tensor([ 6,  8, 10, 12])